In [1]:
import numpy as np

In [17]:
M = 10000
N = 10000
dens = 4 / np.pi
dens

1.2732395447351628

In [8]:
masas_l = np.linspace(1, 1.5, 20)
masas_l

array([1.        , 1.02631579, 1.05263158, 1.07894737, 1.10526316,
       1.13157895, 1.15789474, 1.18421053, 1.21052632, 1.23684211,
       1.26315789, 1.28947368, 1.31578947, 1.34210526, 1.36842105,
       1.39473684, 1.42105263, 1.44736842, 1.47368421, 1.5       ])

In [9]:
radios_l = np.sqrt(masas_l / 4)
radios_l

array([0.5       , 0.50653623, 0.51298918, 0.51936196, 0.52565748,
       0.5318785 , 0.53802759, 0.54410719, 0.5501196 , 0.55606702,
       0.56195149, 0.56777497, 0.57353933, 0.57924633, 0.58489765,
       0.59049489, 0.59603956, 0.60153313, 0.60697698, 0.61237244])

In [10]:
masas_s = np.linspace(1, 0.5, 20)
masas_s

array([1.        , 0.97368421, 0.94736842, 0.92105263, 0.89473684,
       0.86842105, 0.84210526, 0.81578947, 0.78947368, 0.76315789,
       0.73684211, 0.71052632, 0.68421053, 0.65789474, 0.63157895,
       0.60526316, 0.57894737, 0.55263158, 0.52631579, 0.5       ])

In [11]:
radios_s = np.sqrt(masas_s / 4)
radios_s

array([0.5       , 0.49337719, 0.48666426, 0.47985743, 0.47295265,
       0.46594556, 0.45883147, 0.45160532, 0.44426166, 0.43679454,
       0.42919754, 0.42146362, 0.4135851 , 0.40555355, 0.39735971,
       0.3889933 , 0.38044296, 0.37169597, 0.36273813, 0.35355339])

In [16]:
n_l = (M / (8 * radios_l**2)).astype(int)
n_l

array([5000, 4871, 4750, 4634, 4523, 4418, 4318, 4222, 4130, 4042, 3958,
       3877, 3800, 3725, 3653, 3584, 3518, 3454, 3392, 3333])

In [18]:
n_s = N - n_l
n_s

array([5000, 5129, 5250, 5366, 5477, 5582, 5682, 5778, 5870, 5958, 6042,
       6123, 6200, 6275, 6347, 6416, 6482, 6546, 6608, 6667])

In [20]:
masas_totales = n_l * radios_l**2 * 4 + n_s * radios_s**2 * 4
masas_totales

array([10000.        ,  9993.21052632,  9973.68421053,  9942.21052632,
        9899.57894737,  9846.84210526,  9784.63157895,  9713.36842105,
        9633.68421053,  9546.21052632,  9451.57894737,  9349.84210526,
        9242.10526316,  9127.63157895,  9007.47368421,  8882.10526316,
        8752.        ,  8616.73684211,  8476.63157895,  8333.        ])